### PR TITLE
[WIP] run_meg_tutorial.py

### PR DESCRIPTION
**Pull request by jaeilepp**
Python equivalent of run_meg_tutorial.sh. Runs through on my computer. Apparently ``make_inverse_operator`` for fixed orientation isn't implemented in python. For comparison: https://github.com/mne-tools/mne-scripts/blob/master/sample-data/run_meg_tutorial.sh

### CODE REVIEW

**Comment by dengemann** [comment]
We should have something like mne.workflows
and put a prpoer function here to produce all the anatomy for one subject ...

**Comment by agramfort** [comment]
+1 for merge.

We should have a mne command for anatomy workflow

And a detailed tutorial to explain these steps.

**Comment by dengemann** [comment]
> We should have a mne command for anatomy workflow

And then you need a function for that. Any command should be accessible as a function so integration in a python script is easier.

**Comment by agramfort** [comment]
thanks @jaeilepp

**Pull request merged**
