### PR TITLE
WIP: Add brainstorm dataset freesurfer recon

### PR DESCRIPTION
**Pull request by mainakjas**

### CODE REVIEW

**Comment by agramfort** [comment]
Could you call the folder brainstorm-data here and as path in examples folder?

**Comment by mainakjas** [comment]
You mean MNE-brainstorm-data (because that's how the other's are named -- with an MNE prefix) ? Actually, I'm thinking of three separate archives (bst_auditory, bst_resting and bst_raw) which have their own MEG and subjects folder. And each of them will reside inside the MNE-brainstorm-data folder.

I think I'm good here. The script seems to be running without any errors. The first archive is ready, the other two are still being processed but I don't expect any major mishaps since the first iteration of the loop went well :)

**Comment by mainakjas** [comment]
Each archive will be downloaded separately / on-demand instead of downloading all three at once, which will be huge -- 5 or 6 GB as opposed to only 1 or 2 GB.

**Comment by agramfort** [comment]
> You mean MNE-brainstorm-data (because that's how the other's are named -- with an MNE prefix) ? Actually, I'm thinking of three separate archives (bst_auditory, bst_resting and bst_raw) which have their own MEG and subjects folder. And each of them will reside inside the MNE-brainstorm-data folder.
> 
Sounds good. Just make sure brainstorm is lower case as it's not an acronym

**Pull request merged**
