### PR TITLE
Fix somato conversion script

### PR DESCRIPTION
**Pull request by sappelhoff**
see discussion here: https://github.com/mne-tools/mne-python/issues/6770

### CODE REVIEW

**Comment by sappelhoff** [comment]
> Looks good to me. Can you try removing the workaround in examples/inverse/plot_dics_source_power.py just to double-check things work?

will do, but first I'll need to upload the new data to OSF and adjust hashes etc.

**Comment by larsoner** [comment]
No I mean just:

1. Run example
2. Remove workaround from example, ensure it fails
3. Locally copy the file over to your `mne_data`
4. Run example, ensure it now works
5. Proceed with OSF, MNE PR, etc.

**Comment by sappelhoff** [comment]
makes more sense, thanks. How do I run a specific example?

**Comment by larsoner** [comment]
`python -ui examples/inverse/plot_dics_source_power.py`

**Comment by larsoner** [comment]
(I know you probably meant "as part of sphinx build" but I don't think it's necessary here, you can just eyeball the outputs and failures in your own testing. But for future reference to do it the Sphinx-gallery way it would be in the `doc` folder to rune `PATTERN=plot_dics_source_power make html_dev-pattern`)

**Comment by larsoner** [comment]
Thanks @sappelhoff

**Pull request merged**
